name: "🐛 Bug"
description: "에러나 오류가 나타나는 내용"
title : "[MEMBER/GAME/RANKING] "
labels: [":bug: bug"]
projects: ["beyond-SW-Camp-14th-5rE5/5"]
body:
  - type: textarea
    attributes:
      label: 📄 설명
      description: 나타난 버그에 대한 설명을 작성해 주세요.
      placeholder: 최대한 자세하게 작성해주세요!
      value:
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✅ 작업할 내용
      description: 해결을 위해 해야 할 일을 체크박스 형태로 작성해주세요.
      placeholder: 최대한 세분화 해서 적어주세요!
      value:
    validations:
      required: true
